### ISSUE TITLE
CP PDA PRMT&DMTE Vanishing

### ISSUE THREAD

**Issue by YuhBoyDeath** [urnotnick/impulse-issues#42] opened 2022-03-10 21:26 UTC
**Describe the bug**
Promote and Demote menu of CP PDA just disappears randomly.

**To reproduce**
Steps to reproduce the behaviour:
1. Flag onto CP Supervisor. 
2. Press F6
3. Have a chance for the error to occur

**Expected behaviour**
For the promote/demote menu to be on my PDA so I can do either of those tasks.

**Screenshots**

**impulse version (press F1 in the bottom right):**
 1.9.2

**Lua error**
gamemodes/landis-hl2rp/plugins/dispatch/vgui/cl_pda.lua:447: attempt to call method 'GetPropertyOwner' (a nil value)
    1. SetupPDA - gamemodes/landis-hl2rp/plugins/dispatch/vgui/cl_pda.lua:447
        3. Init - gamemodes/landis-hl2rp/plugins/dispatch/vgui/cl_pda.lua:15
            4. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
                5. v - gamemodes/landis-hl2rp/plugins/dispatch/cl_hooks.lua:3
                    6. Run - lua/includes/modules/hook.lua:96
                        7. unknown - gamemodes/impulse/gamemode/core/hooks/cl_hooks.lua:77

**Additional context**
It's completely random as far as I'm aware and not possible to reproduce at will

**Comment by urnotnick** [comment] 2022-03-10 23:11
Duplicate of issue #37

**Closed** 2022-03-22 12:28 UTC
Labels: bug, duplicate, hl2rp
