### ISSUE TITLE
Curfew Status no longer shows up on Combine HUD

### ISSUE THREAD

**Issue by ThatBapGuy** [urnotnick/impulse-issues#204] opened 2023-02-21 00:52 UTC
**Describe the bug**
Curfew Status no longer shows up under the Compass.

**To reproduce**
Steps to reproduce the behaviour:
1. Go on Civil Protection
2. Wait for Curfew
3. See no Curfew Status under Compass

**Expected behaviour**
Curfew to be reminded underneath the compass.

**Screenshots**

**impulse version (press F1 in the bottom right):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by justinbrick** [comment] 2023-03-18 22:01
duplicate of #173

**Closed as not planned by justinbrick** 2023-03-18 22:01 UTC
Labels: bug, hl2rp
