### ISSUE TITLE
Description issue

### ISSUE THREAD

**Issue by SSteffan** [urnotnick/impulse-issues#115] opened 2022-11-15 23:44 UTC
**Describe the bug**
The server forgets your job descriptions after every restart

**To reproduce**
Steps to reproduce the behaviour:
1. Server restarts
1. Spawn in, or change to any class
2. "you need a description" text box appears
2. Forces you to write a new description

**Expected behaviour**
The server should remember all job descriptions past restart.

**Screenshots**
https://cdn.discordapp.com/attachments/917456662674153472/1042194876227395674/image.png

**impulse version (press F1 in the bottom right):**
1.11.2

**Lua error**
N/A

**Additional context**
Would be a good idea to add the ability to check/edit your own description on the go

**Comment by elrobusto** [comment] 2022-11-15 23:45
@SSteffan same issue already exists #109

**Comment by sophfee** [comment] 2022-11-15 23:46
Duplicate of #109, contribute to that.

**Closed as completed by sophfee** 2022-11-15 23:46 UTC
Labels: duplicate
